echo "
                   ..',;::cclllllcc::;,'..
           .,lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMNKOdc,.
        ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,
      ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK.
     xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo
    xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd
   .MMMMMMNNXKK0KKKXNMMMMMMMMMMMMMMMMMMMNXKKK0KKXNNMMMMMM.
   XMMMMMOc'.    .':dKNNMMMMMMMMMMMMMNNKd:'.    .'cOMMMMMK
  .MMMMXdok00Okdl:'.  'xWMMMMMMMMMMMWx'  .':ldkO00kddXMMMM
  :MMMMMMMMMMMMMWWXKkl,  lWMMMMMMMWl  ,lkKXWWMMMMMMMMMMMMM,
  kMMMMMMMMMMMMMMMMMWX0X0xNMMMMMMMWxOX0XWMMMMMMMMMMMMMMMMMd
  NMMMMMMMMMMMMWWWWMMMWXKMMMMMMMMMMMKXWMMMWWWWMMMMMMMMMMMMO
  WMMMMMMMMNNKkkxldxkKWMWXMWMMMMMWMXWMWKkxdlxkkKNNMMMMMMMMX
  WMMMWMMWKK; ..00.'. ,0WWWNMMMMMNWWW0,..'.00.. :KKNMMWMMMN
  XWMMNKKKKXOl;;,.,:;:xXWMMXMMMMMXMMWXx:;:;.,;;lOXKKKKNMMW0
  0MMWWMMMMMMWNNNXXNNWMMMMXXMMMMMXXMMMMWNNXXNNNWMMMMMMWWMMx
  oMMMMMMMMMMMMMMMMMMMMMMW0XMMMMMX0WMMMMMMMMMMMMMMMMMMMMMM:
  ,MMMMMMMMMMMMMMMMMMMMMW00NMMMMMN00WMMMMMMMMMMMMMMMMMMMMM.
   MMMMMMMMMMMMMMMMMMMMXXWXWMMMMMWXWXNMMMMMMMMMMMMMMMMMMMM
   WMMMMMMMMMMMMMMMWWWXWMMXMMMMMMMXMMWKWWWMMMMMMMMMMMMMMMX
   oMMNXNWWMMWWNNNNNMNNMMMKMMMMMMMKMMMNNMNNNNNWWMMWWNXNMMc
   .MMMKKWl,kWWWMMMMMMWMOo0XNNWNNXKdkMWMMMMMMWWWk,cWKKMMM
    KMMWKXN, :WMMMMMMMMMMMKoxxkxxoKMMMMMMMMMMMWc ;NX0WMM0
    'MMMW0XMx .kMMMMMMMMX:   ;o;   :KMMMMMMMMO. xMX0WMMM.
     KMMMWKKWN: .;;;,'..    OMMMO    ..',;;;. ;NWKKWMMMx
      MMMMMK0XWXxolc::::..'xOOOOOx,..::::cloxKWX0KMMMMM
      ,MMMMMNXNNWWMMMMMMWXKKKKKKKKKXWMMMMMMWWNNXNMMMMM.
       .MMMMMWXWMMWMMMMMMMMMMMMMMMMMMMMMMMWMMWXWMMMMM
         xMMMMMNNMMMMMMMMMM0,,,,,0MMMMMMMMMMNNMMMMMo
           XMMMMMWMMMMMMMMMMl   oMMMMMMMMMMWMMMMM0
             XMMMMMMMMMMMMMM;   ;MMMMMMMMMMMMMMk
               xMMMMMMMMMMMX     NMMMMMMMMMMMl
                 'MMMMMMMMMK     XMMMMMMMMM.
                    NMMMMMMM     MMMMMMMX
                      ,MMMMMl   lMMMMM.
                          NMW, ,WMX

    ██╗  ██╗ █████╗  ██████╗██╗  ██╗       ██████╗ ███████╗
    ██║  ██║██╔══██╗██╔════╝██║ ██╔╝      ██╔═══██╗██╔════╝
    ███████║███████║██║     █████╔╝ █████╗██║   ██║███████╗
    ██╔══██║██╔══██║██║     ██╔═██╗ ╚════╝██║   ██║╚════██║
    ██║  ██║██║  ██║╚██████╗██║  ██╗      ╚██████╔╝███████║
    ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝       ╚═════╝ ╚══════╝v1.21 " | lolcat
